### ISSUE TITLE
Outputs wrong 'repo: ' anchor

### ISSUE THREAD

**Issue by Munter** [montogeek/remark-extract-anchors#2]
When passing a markdown file like the one for babel-minify-webpack-plugin through this tool, it outputs the anchors for the headings, but it also wrongly outputs an anchor at the top of the list with the following content:

```json
{
  "title": "repo: ",
  "id": "repo-httpsgithubcomwebpack-contribbabel-minify-webpack-plugin"
},
```

The result of this can be seen in the left hand menu of all webpack loaders: https://webpack.js.org/loaders/babel-loader/

![image](https://user-images.githubusercontent.com/331790/63304637-fe38a280-c2e3-11e9-91c2-dafaf2bafb91.png)

## Example markdown:

```md
---
title: BabelMinifyWebpackPlugin
source: https://raw.githubusercontent.com/webpack-contrib/babel-minify-webpack-plugin/master/README.md
edit: https://github.com/webpack-contrib/babel-minify-webpack-plugin/edit/master/README.md
repo: https://github.com/webpack-contrib/babel-minify-webpack-plugin
---
A Webpack Plugin for <a href="https://github.com/babel/minify">babel-minify</a> - A babel based minifier

## Install

... snipped away for brevity

```

## Output:

```json
"anchors": [
  {
    "title": "repo: ",
    "id": "repo-httpsgithubcomwebpack-contribbabel-minify-webpack-plugin"
  },
  {
    "title": "Install",
    "id": "install"
  }
]
```

**Comment by montogeek** [comment]
Will fix it tonight, (in 10 hours).
Thanks

**Comment by montogeek** [comment]
Fixed in https://github.com/montogeek/remark-extract-anchors/releases/tag/v1.0.2.
